name: app
description: "AreYouAProgrammer"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
  - images/placeholder.png
  - fonts/MontserratBold.ttf

  uses-material-design: true
